### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Dan",
  "email": "dan@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "dan@test.com",
  "password": "password"
}

### Recipes Index
GET http://localhost:3000/recipes.json

### Recipes create
POST http://localhost:3000/recipes.json
Content-Type: application/json

{
  "user_id": 1,
  "name": "Chicken Florentine",
  "chef": "Dan",
  "prep_time": 20,
  "cook_time": 90,
  "temperature": 325
}

### Recipes Show
GET http://localhost:3000/recipes/1.json

### Recipes Update
PATCH http://localhost:3000/recipes/2.json
Content-Type: application/json

{
  "chef": "Mary Jane"
}

### Recipes destroy
DELETE http://localhost:3000/recipes/2.json

### Ingredient create
POST http://localhost:3000/ingredients.json
Content-Type: application/json

{
  "recipe_id": 3,
  "name": "peanut butter",
  "measurement": 2
}

### Ingredients Index
GET http://localhost:3000/ingredients.json

### Ingredient Show
GET http://localhost:3000/ingredients/1.json

### Ingredient Update
PATCH http://localhost:3000/ingredients/1.json
Content-Type: application/json

{
  "name": "crunchy peanut butter"
}

### Ingredient Destroy
DELETE http://localhost:3000/ingredients/1.json

### direction create
POST http://localhost:3000/directions.json
Content-Type: application/json

{
  "recipe_id": 5,
  "order": 1,
  "instruction": "boil water or milk"
}

### Direction show
GET http://localhost:3000/directions/1.json

### Direction update
PATCH http://localhost:3000/directions/1.json
Content-Type: application/json

{
  "order": 2
}

### direction destroy
DELETE http://localhost:3000/directions/1.json